### ISSUE TITLE
Progress Bar not usable on notched devices

### ISSUE THREAD

**Issue by freshkaden** [haoict/tiktok-god#10]
![image](https://user-images.githubusercontent.com/66493708/83918244-52632500-a746-11ea-82e4-488dc35f915b.png)
The progress bar appears under the tab bar (iPhone 11), and so you can only see it when scrolling in between videos.

**Comment by TheDoctor40** [comment]
I have the same issue. I also confirmed that is does work properly on my iPhone 7 Plus without the notch but with home button.

**Comment by Mozorianer** [comment]
Can confirm too

**Comment by haoict** [comment]
Updated to v1.6.1. 
Should fix the problem
