### ISSUE TITLE
Download all videos not working 

### ISSUE THREAD

**Issue by megatech1966** [haoict/tiktok-god#12]
Download all videos is not working even after update.

**Comment by haoict** [comment]
To download video, you have to press and hold on video.

**Comment by megatech1966** [comment]
Not working on some videos. No save video option appears

**Comment by haoict** [comment]
Have you turned on "Unlimited Download" in Settings?

**Comment by haoict** [comment]
Could you please send me screenshot after you press and hold on video?

**Comment by megatech1966** [comment]
After your update

**Comment by haoict** [comment]
I can't see your screenshot, here is what I see
![image](https://user-images.githubusercontent.com/7247750/83949992-52584780-a862-11ea-9382-456aa48d972a.png)

**Comment by freshkaden** [comment]
![image](https://user-images.githubusercontent.com/66493708/83952201-307ca780-a805-11ea-892a-a935f8e8a7e9.png)
![image](https://user-images.githubusercontent.com/66493708/83952208-35415b80-a805-11ea-9514-4d54941ea673.png)
Seems to only show up on some videos.

**Comment by megatech1966** [comment]
That’s my point. Because of the latest TikTok update. Your tweak no longer allows all videos to be downloaded.

**Comment by megatech1966** [comment]
Works if I downgrade TikTok to version 16.1.0

**Comment by haoict** [comment]
Should be fixed in v1.6.2
https://github.com/haoict/tiktok-god/releases/tag/v1.6.2

**Comment by megatech1966** [comment]
Yes. Seems to be fixed 👍

**Comment by megatech1966** [comment]
I donated because of your excellent support 👍

**Comment by haoict** [comment]
@megatech1966 
Thanks a lot <3
