### ISSUE TITLE
Watermark issue with downloads 

### ISSUE THREAD

**Issue by Reshael04** [haoict/tiktok-god#16]
v1.6.2 Hasn’t resolved the issue with downloading TikTok videos without the watermark.

**Comment by haoict** [comment]
This is a confirmation that it was resolved. (TikTok 16.3.0)
https://github.com/haoict/tiktok-god/issues/12

Could you leave here a screenshot of the popup when you press and hold on video?

**Comment by Reshael04** [comment]
Yeah the pop up comes up where I can download it without the watermark but when it actually saves onto my device and when I look at it the watermark is still there.

**Comment by Reshael04** [comment]
Is there a email where I could send the screenshot to you as it isn’t allowing me to send it here ?

**Comment by haoict** [comment]
My email is "hao.ict56@gmail.com"

**Comment by Reshael04** [comment]
Hey. As you see in the screenshot I have the option to save it as with no
watermark but when I see the video on my photos app nothing has changed.
