### ISSUE TITLE
When going "live" is not working

### ISSUE THREAD

**Issue by steffanjensen** [haoict/tiktok-god#2]
When i am going live and I have tiktok-god activated it just start to record a video instead of going live, issue is fixed when I deactivate tiktok-god.

**Comment by haoict** [comment]
Could you provide more information, screenshoot or screen recording?
I don't have live mode so I can't test it

**Comment by steffanjensen** [comment]
fixed by changing location to US. Maybe live was not available in the country I had selected (parkistan).

Issue closed.
