### ISSUE TITLE
Hey man I still can’t download the video

### ISSUE THREAD

**Issue by shanekoz** [haoict/tiktok-god#22]
![image](https://user-images.githubusercontent.com/38496071/84592171-d9627c80-ae6d-11ea-847b-452079686575.png)

**Comment by haoict** [comment]
Please send me screen record of how you perform download video,
my email: hao.ict56@gmail.com

**Comment by haoict** [comment]
Kindly check newest version 1.8.0
https://github.com/haoict/tiktok-god/releases/tag/v1.8.0
