### ISSUE TITLE
Can’t comment videos (has creator)

### ISSUE THREAD

**Issue by jes6mac** [haoict/tiktok-god#35]
When we receive a notification for a comment on our video we can't comment it in the app if we tap this notification. We have to come back to our profile and open video + find the comment. 
(Works well without the tweak)
*hope you understand

**Comment by jes6mac** [comment]
Issue not here if I disable progress bar.

**Comment by haoict** [comment]
Should be fixed in v1.9.2
https://github.com/haoict/tiktok-god/releases/tag/v1.9.2
