### ISSUE TITLE
Bản cập nhật mới

### ISSUE THREAD

**Issue by nguyenvandung1** [haoict/tiktok-god#64]
Mong a sớm ra bản cập nhật mới vì bản tiktok mới nhất không còn hỗ trợ

**Comment by haoict** [comment]
Bạn có thể mô tả chi tiết tính năng nào bị lỗi không?

**Comment by nguyenvandung1** [comment]
bản tiktok god không sử dụng được nữa ạ

Vào Th 6, 12 thg 2, 2021 lúc 22:28 Hao Nguyen <notifications@github.com> đã
viết:

**Comment by haoict** [comment]
Updated to 2.0.0
