### ISSUE TITLE
After Latest Update, Features Not Working

### ISSUE THREAD

**Issue by pinustrobus** [haoict/tiktok-god#72]
### Environment
- Platform+version: **iOS 14.2**
- Tweak version: **1.10.0**
- Do you have jailbreak detection bypass tweaks: Liberty and KernByPass. Neither bypassing for TikTok
- If yes, are you sure that it does not block this tweak: **Yes**

### Bug Report

After latest update for the app TikTok, I can no longer hide the watermark. I can no longer download video clips. Other features of your tweak might not be working, but I hit the most important aspects for me.

**Comment by haoict** [comment]
Hi
After the update, can you see this button?
![image](https://user-images.githubusercontent.com/7247750/110164197-5edef000-7e34-11eb-92c3-e2dbfee216ed.jpeg)

**Comment by pwn27sbx** [comment]
The same thing happens to me, it's as if the tweak didn't work;  IPhone X iOS 14.3

**Comment by pinustrobus** [comment]
> Hi
> After the update, can you see this button?
> 
> <img alt="Facebook No Ads" width="414" src="https://user-images.githubusercontent.com/7247750/110164197-5edef000-7e34-11eb-92c3-e2dbfee216ed.jpeg">

I cannot see the icon. It looks as thoug TikTok is vanilla version.

**Comment by techx-guy** [comment]
Same

**Comment by haoict** [comment]
Updated to 1.11.0. Please check
https://github.com/haoict/tiktok-god/releases/tag/v1.11.0
