### ISSUE TITLE
Only works once

### ISSUE THREAD

**Issue by megatech1966** [haoict/tiktok-god#73]
### Environment
- Platform+version: **iOS 13.7** 
- Tweak version: **1.10.0** 
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **Yes**
- If yes, are you sure that it does not block this tweak: **Yes/No**

### Bug Report

Note: Providing steps to reproduce, screenshot or screen recording are always helpful!

For some reason this tweak only works once. I close TikTok the tweak doesn’t work at all. I have to downgrade TikTok to version 18.0.0 for it to work all the time. I have a iPhone X with checkra1n. Also failed with the previous version of TikTok God. Works fine on my iPad Air 2 though.

**Comment by megatech1966** [comment]
For some reason this tweak only works once. I close TikTok the tweak doesn’t work at all. I have to downgrade TikTok to version 18.0.0 for it to work all the time. I have a iPhone X with checkra1n. Also failed with the previous version of TikTok God. Works fine on my iPad Air 2 though.

**Comment by haoict** [comment]
Updated to 1.11.0. Please check
https://github.com/haoict/tiktok-god/releases/tag/v1.11.0
