### ISSUE TITLE
Can use it no more

### ISSUE THREAD

**Issue by claytonabcdef** [haoict/tiktok-god#76]
So after its update i cant use it i tried updating the tweak but it doesnt work

**Comment by haoict** [comment]
Please give more details

**Comment by claytonabcdef** [comment]
Its like when i equip download without watermark it doesnt work when i equip anything nothing works

**Comment by claytonabcdef** [comment]
Its like when i use the download without watermark it downloaded with a tiktok watermark and everything that i equip it still doesnt work

**Comment by haoict** [comment]
Close due to no detail. You should follow bug report template
