### ISSUE TITLE
Use native Tik Tok video slider

### ISSUE THREAD

**Issue by NSExceptional** [haoict/tiktok-god#86]
Tik Tok apparently has a native video slider now! It only appears on longer videos I think. Can you enable it for all videos? It is better than the one in this tweak (no offense, it's just more polished)

**Comment by haoict** [comment]
Done, updated to v2.0.0

**Comment by NSExceptional** [comment]
Amazing 😭 thank you

Unfortunately now there's a bug with the position of the UI over videos, I'll open a new issue 😅
