### ISSUE TITLE
CPU increase when installed.

### ISSUE THREAD

**Issue by steffanjensen** [haoict/tiktok-god#9]
I had issue, where cpu and battery drained faster with jailbreak, the issue disappeared when i disabled tiktok-god.

With tiktok-god installed:
2-4% cpu
Without tiktok-god installed:
0.10-1%

So it's a pretty heavy drop if i disable tiktok-god tweak with ccleaner pro.

I saw that something called mediaserverd was enabled with tiktok-god and that increase the cpu with 2%.

**Comment by haoict** [comment]
I don't have this problem on my devices. Let me monitor it more

**Comment by andrewem** [comment]
Hi Steffan,

I'm looking to get all the followings and followers of a specified tiktok user and get the results on a notepad/excel or something else.

I can pay if you can do that for me.

**Comment by andrewem** [comment]
Hi @steffanjensen 

I'm looking to get all the followings and followers of a specified tiktok user and get the results on a notepad/excel or something else.

I could'n see any email or some other way to contact you that's why I'm writing here xD

I can pay if you can do that for me.

**Comment by steffanjensen** [comment]
> 
> 
> Hi @steffanjensen
> 
> I'm looking to get all the followings and followers of a specified tiktok user and get the results on a notepad/excel or something else.
> 
> I could'n see any email or some other way to contact you that's why I'm writing here xD
> 
> I can pay if you can do that for me.

Hi, I pretty busy at this moment but thanks for the offer.
