### ISSUE TITLE
Progress bar not working on latest TikTok

### ISSUE THREAD

**Issue by rutgerrrrr** [haoict/tiktok-god#92]
### Environment
- Platform+version: **iOS 13.5** 
- Tweak version: **1.12.2** 
- TikTok version: 20.71
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...): **Yes**
- If yes, are you sure that it does not block this tweak: **Yes**

### Bug Report

I've updated both TikTok and the tweak to the latest versions. After updating the progress bar stopped working correctly. Every time I try to use it, it just snaps back to its original position like it's disabled. Everything else seems to work fine and the icons show up in the upper right corner. The native progress bar works just fine though when it shows up.

**Comment by haoict** [comment]
Updated to v2.0.0
