### ISSUE TITLE
[Bug] Video overlay is now shifted upwards

### ISSUE THREAD

**Issue by NSExceptional** [haoict/tiktok-god#96]
### Environment
- Platform+version: **iOS 14** / latest version
- Tweak version: **2.0.0**
- Jailbreak detection bypass tweaks: **No**

### Report

Screenshot:

<img width="30%" height="30%" src="https://user-images.githubusercontent.com/8371943/133695960-1f406b74-3589-497c-bbcd-d80e785bdb46.png">

**Comment by haoict** [comment]
Fixed: https://github.com/haoict/tiktok-god/releases/tag/v2.1.0
Please check!
